config/routes.rb
Rails.application.routes.draw do
  get 'pdf/certified/:id'                        => 'pdf#certified',                         as: :certified
  resources :trees
  resources :trees
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

	authenticated :user do
		root 'home#index', as: 'authenticated_root'
	end
	devise_scope :user do
		root 'devise/sessions#new'
	end
end

app/models/tree.rb
class Tree < ActiveRecord::Base
  belongs_to :user

  attr_accessor :endereco

end

app/models/user.rb
class User < ActiveRecord::Base
  # nInclude default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.name = auth.info.name
			user.is_facebook = true
			user.provider = auth.provider
			user.uid = auth.uid
			user.password = Devise.friendly_token[0,20]
			
		end
	end

	def admin?
		self.admin == true
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!

  def test_user
    if !current_user.admin? && @tree.user_id != current_user.id
      # ADD AQUI FLASH PARA MENSAGEM DE ERRO
      redirect_to trees_path
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  before_action :set_tree
  before_action :authenticate_user!
  before_action :test_user

  def certified
    render template: 'pdf/certified',
      handlers: [:erb],
      formats: [:pdf],
      page_size: 'A4',
      pdf: "Certificado #{l(Date.current)}",
      #layout: 'layouts/application.html',
      #header: { html: { template: 'layouts/pdf/header', handlers: [:erb], formats: [:pdf] }},
      #footer: { html: { template: 'layouts/pdf/footer', handlers: [:erb], formats: [:pdf] }},
      #margin: { bottom: 15, top: 50, right: 10, left: 10 },
      show_as_html: false,
      #disposition: 'attachment', OPÇÃO PARA BAIXAR AUTOMATICAMENTE
      encoding: 'UTF-8'
  end

  private
    def set_tree
      @tree = Tree.find(params[:id])
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :test_user, only: [:show, :edit, :update, :destroy]

  require 'securerandom'

  def index
    if current_user.admin?
      @trees = Tree.all
    else
      @trees = Tree.where(user_id: current_user.id)
    end
    
  end

  def show
    @tree.endereco = "#{@tree.street}, #{@tree.district}, #{@tree.city} - #{@tree.state}"
  end

  def new
    @tree = Tree.new
    @tree.numbering = Faker::Number.number(10)
  end

  def edit
  end

  def create
    @tree = Tree.new(tree_params)
    continue = true
    trees = Tree.all
    @tree.user_id = current_user.id
    numbering_aux = @tree.numbering
    while continue == true
      finder = trees.where("numbering = ?", numbering_aux).count
      if finder > 0
        numbering_aux = SecureRandom.random_number 10000
      else  
        continue = false
        @tree.numbering = SecureRandom.random_number 10000
      end
    end
    @tree.numbering = numbering_aux
    if @tree.save
      redirect_to trees_path
    else
      render :new
    end
  end

  def update
    if @tree.update(tree_params)
      redirect_to trees_path
    else
      render :edit
    end
  end

  def destroy
    if @tree.destroy
      redirect_to trees_path
    end
  end

  

  private
    def set_tree
      @tree = Tree.find(params[:id])
    end

    def tree_params
      params.require(:tree).permit(:name, :user_id, :requester, :species, :date_planting, :who_planted, :old_name, :street, :city, :number, :district, :country, :state, :lat, :long, :numbering, :authorization, :date_solicitation)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		sign_in_and_redirect @user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/user/omniauth_callbacks_helper.rb
module User::OmniauthCallbacksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseFacebookOauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <% if !current_user.admin? && current_user.provider.blank? %>
    <%= link_to "Edit profile", edit_user_registration_path %> |
  <% end %>
  <%= link_to "Árvores cadastradas", trees_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path  %> |
  <%= link_to "Login", new_user_session_path  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pdf/certified.pdf.erb
<title>Certificado</title>
<h2>Certificado</h1>
<p>
  <strong>Nome:</strong>
  <%= @tree.name %>
</p>

<p>
  <strong>Solicitante:</strong>
  <%= @tree.requester %>
</p>

<p>
  <strong>Espécie:</strong>
  <%= @tree.species %>
</p>

<p>
  <strong>Data de Plantio:</strong>
  <%= @tree.date_planting.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Quem plantou:</strong>
  <%= @tree.who_planted %>
</p>

<p>
  <strong>Nome que já possuiu ou atual:</strong>
  <%= @tree.old_name %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @tree.endereco %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @tree.lat %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @tree.long %>
</p>

<p>
  <strong>Código de Identificação:</strong>
  <%= @tree.numbering %>
</p>

<p>
  <strong>Autorização:</strong>
  <%= @tree.authorization %>
</p>

<p>
  <strong>Data de solicitação:</strong>
  <%= @tree.date_solicitation.strftime("%d/%m/%Y") %>
</p>

app/views/trees/_form.html.erb
  <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map-canvas'), {
          center: {lat: -15.7976667, lng: -47.886083799999994},
          zoom: 4
        });
       var geocoder = new google.maps.Geocoder();
       google.maps.event.addListener(map, 'click', function(event) {
        geocoder.geocode({'latLng': event.latLng}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            if (results) {
              console.log(results[0].address_components)
              var number
              var street 
              var district
              var city 
              var state 
              var country
              
              country = state = city = district = street = number = "Sem dados"
              //console.log(results[0].address_components[6].long_name)
              //console.log(results[0].address_components[7].long_name)
              //console.log(results[0].address_components[8].long_name)
              
              for(var i = 0; i<results[0].address_components.length; i++){
                if(results[0].address_components[i].types[0] == "street_number"){
                  number = results[0].address_components[i].short_name
                }else{
                  if(results[0].address_components[i].types[0] == "route"){
                    street = results[0].address_components[i].short_name
                  }else{
                    if(results[0].address_components[i].types[0] == "country"){
                      country = results[0].address_components[i].long_name      
                    }else{
                      if(results[0].address_components[i].types[0] == "administrative_area_level_1"){
                        state = results[0].address_components[i].short_name  
                      }else{
                        if(results[0].address_components[i].types[0] == "administrative_area_level_2"){
                          city = results[0].address_components[i].short_name                   
                        }else{
                          if(results[0].address_components[i].types[0] == "political"){
                            district = results[0].address_components[i].short_name
                          }
                        }
                      }
                    }
                  }
                }
              }

              var latitude = results[0].geometry.location.lat();
              var longitude = results[0].geometry.location.lng();

              swal({
                title: "Você tem certeza que deseja escolher este endereço?",
                text: street + ", " + district + " - " + state + ", " + city + " " + country,
                icon: "warning",
                buttons: ["Cancelar", "Confirmar"],
                dangerMode: false,
              })
              .then((willDelete) => {
                if (willDelete) {
                  var form_lat = document.getElementById('tree_lat')
                  var form_long = document.getElementById('tree_long')
                  var form_street = document.getElementById('tree_street')
                  var form_country = document.getElementById('tree_country')
                  var form_state = document.getElementById('tree_state')
                  var form_city = document.getElementById('tree_city')
                  var form_number = document.getElementById('tree_number')
                  var form_district = document.getElementById('tree_district')
                  
                  form_district.value = district
                  form_number.value = number
                  form_city.value = city
                  form_state.value = state
                  form_country.value = country
                  form_street.value = street
                  form_lat.value = latitude
                  form_long.value = longitude
                  swal("Endereço selecionado com sucesso!", {
                    icon: "success",
                  });
                }
              });
            }
          }
        });
      });
    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCbNFJ-u2giKjZODirkdXz8dUKW1S3xjjg&callback=initMap"
    async defer></script>
  
<%= form_for(@tree) do |f| %>
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Quem requisitou o cadastro?" %><br>
    <%= f.text_field :requester %>
  </div>
  <div class="field">
    <%= f.label "Nome da espécie?" %><br>
    <%= f.text_field :species %>
  </div>
  <div class="field">
    <%= f.label "Data do plantio" %><br>
    <%= f.date_select :date_planting %>
  </div>
  <div class="field">
    <%= f.label "Quem plantou?" %><br>
    <%= f.text_field :who_planted %>
  </div>
  <div class="field">
    <%= f.label "Título ou nome que já possuí ou possuiu" %><br>
    <%= f.text_field :old_name %>
  </div>
  <div class="field">
    <%= f.label "Rua" %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label "Bairo / Distrito" %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label "Complemento" %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "Cidade" %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label "Estado" %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label "País" %><br>
    <%= f.text_field :country %>
  </div>
  
  
  <div class="field">
    <%= f.hidden_field :lat %>
  </div>
  <div class="field">
    <%= f.hidden_field :long %>
  </div>
  <div class="field">
    <%= f.hidden_field :numbering %>
  </div>


  <div class="field">
    <%= f.label "Autorização pré-cadastro cred carbono" %><br>
    <%= f.text_field :authorization %>
  </div>
  <div class="field">
    <%= f.label "Data da solicitação" %><br>
    <%= f.date_select :date_solicitation %>
  </div>
  <div id="map-canvas"></div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editando <%= @tree.name%></h1>

<%= render 'form' %>

<%= link_to 'Voltar', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Árvores cadastradas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quem resquisitou?</th>
      <th>Espécie</th>
      <th>Data de plantio</th>
      <th>Quem plantou</th>
      <th>Nome antigo ou atual</th>
      <th>Endereço</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Código</th>
      <th>Autorização carbono</th>
      <th>Data da solicitação</th>
      <th>Opções</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.name %></td>
        <td><%= tree.requester %></td>
        <td><%= tree.species %></td>
        <td><%= tree.date_planting.strftime("%d/%m/%Y") %></td>
        <td><%= tree.who_planted %></td>
        <td><%= tree.old_name %></td>
        <td><%= tree.endereco %></td>
        <td><%= tree.lat %></td>
        <td><%= tree.long %></td>
        <td><%= tree.numbering %></td>
        <td><%= tree.authorization %></td>
        <td><%= tree.date_solicitation.strftime("%d/%m/%Y") %></td>
        <td>
          <%= link_to 'Show', tree %>
          <%= link_to 'Edit', edit_tree_path(tree) %>
          <%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar árvore', new_tree_path %>

app/views/trees/new.html.erb
<h1>Cadastrando árvore</h1>

<%= render 'form' %>

<%= link_to 'Voltar', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tree.name %>
</p>

<p>
  <strong>Solicitante:</strong>
  <%= @tree.requester %>
</p>

<p>
  <strong>Espécie:</strong>
  <%= @tree.species %>
</p>

<p>
  <strong>Data de Plantio:</strong>
  <%= @tree.date_planting.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Quem plantou:</strong>
  <%= @tree.who_planted %>
</p>

<p>
  <strong>Nome que já possuiu ou atual:</strong>
  <%= @tree.old_name %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @tree.endereco %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @tree.lat %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @tree.long %>
</p>

<p>
  <strong>Código de Identificação:</strong>
  <%= @tree.numbering %>
</p>

<p>
  <strong>Autorização:</strong>
  <%= @tree.authorization %>
</p>

<p>
  <strong>Data de solicitação:</strong>
  <%= @tree.date_solicitation.strftime("%d/%m/%Y") %>
</p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>